#!/bin/sh

#cleanup
rm-rf obj_dir
rm_f counter.vcd

#run verilator to transalte verilog into C++,including C++ testbench
verilator -Wall --cc --trace counter.sv --exe counter_tb.cpp

# building C++ project via make automatically generated by verilator
make -j -C obj_dir/ -f Vcounter.mk Vcounter

# run executable simulation file
obj_dir/Vcounter